# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orden.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'orden.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0borden.proto\"H\n\x08\x43ustomer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"<\n\x07Vehicle\x12\x14\n\x0cmanufacturer\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"A\n\x06\x43ompra\x12\x1b\n\tvehiculos\x18\x01 \x03(\x0b\x32\x08.Vehicle\x12\x1a\n\x07\x63liente\x18\x02 \x01(\x0b\x32\t.Customer\"!\n\x0e\x43ompraResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\rCompraService\x12*\n\x0eRealizarCompra\x12\x07.Compra\x1a\x0f.CompraResponseB\x0fZ\r./orden;ordenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orden_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./orden;orden'
  _globals['_CUSTOMER']._serialized_start=15
  _globals['_CUSTOMER']._serialized_end=87
  _globals['_VEHICLE']._serialized_start=89
  _globals['_VEHICLE']._serialized_end=149
  _globals['_COMPRA']._serialized_start=151
  _globals['_COMPRA']._serialized_end=216
  _globals['_COMPRARESPONSE']._serialized_start=218
  _globals['_COMPRARESPONSE']._serialized_end=251
  _globals['_COMPRASERVICE']._serialized_start=253
  _globals['_COMPRASERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
