# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orden_pb2 as orden__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orden_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RealizarCompra = channel.unary_unary(
                '/CompraService/RealizarCompra',
                request_serializer=orden__pb2.Compra.SerializeToString,
                response_deserializer=orden__pb2.CompraResponse.FromString,
                _registered_method=True)


class CompraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RealizarCompra(self, request, context):
        """Método para realizar una compra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RealizarCompra': grpc.unary_unary_rpc_method_handler(
                    servicer.RealizarCompra,
                    request_deserializer=orden__pb2.Compra.FromString,
                    response_serializer=orden__pb2.CompraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CompraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CompraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RealizarCompra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CompraService/RealizarCompra',
            orden__pb2.Compra.SerializeToString,
            orden__pb2.CompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
