// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: orden.proto

package orden

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Nombre del cliente
	Lastname string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"` // Apellido del cliente
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`       // Correo electrónico del cliente
	Phone    string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`       // Teléfono del cliente
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_orden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_orden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_orden_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Vehicle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"` // Fabricante del vehículo
	Model        string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`               // Modelo del vehículo
	Year         int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`                // Año del vehículo
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_orden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_orden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_orden_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Compra struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehiculos []*Vehicle `protobuf:"bytes,1,rep,name=vehiculos,proto3" json:"vehiculos,omitempty"` // Lista de vehículos comprados
	Cliente   *Customer  `protobuf:"bytes,2,opt,name=cliente,proto3" json:"cliente,omitempty"`     // Cliente que realiza la compra
}

func (x *Compra) Reset() {
	*x = Compra{}
	mi := &file_orden_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compra) ProtoMessage() {}

func (x *Compra) ProtoReflect() protoreflect.Message {
	mi := &file_orden_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compra.ProtoReflect.Descriptor instead.
func (*Compra) Descriptor() ([]byte, []int) {
	return file_orden_proto_rawDescGZIP(), []int{2}
}

func (x *Compra) GetVehiculos() []*Vehicle {
	if x != nil {
		return x.Vehiculos
	}
	return nil
}

func (x *Compra) GetCliente() *Customer {
	if x != nil {
		return x.Cliente
	}
	return nil
}

type CompraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Mensaje de respuesta del servidor
}

func (x *CompraResponse) Reset() {
	*x = CompraResponse{}
	mi := &file_orden_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompraResponse) ProtoMessage() {}

func (x *CompraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orden_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompraResponse.ProtoReflect.Descriptor instead.
func (*CompraResponse) Descriptor() ([]byte, []int) {
	return file_orden_proto_rawDescGZIP(), []int{3}
}

func (x *CompraResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_orden_proto protoreflect.FileDescriptor

var file_orden_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a,
	0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x57, 0x0a, 0x07, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x55,
	0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x61, 0x12, 0x26, 0x0a, 0x09, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x75, 0x6c, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73,
	0x12, 0x23, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x3b, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x61, 0x12, 0x07, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x61, 0x1a, 0x0f, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orden_proto_rawDescOnce sync.Once
	file_orden_proto_rawDescData = file_orden_proto_rawDesc
)

func file_orden_proto_rawDescGZIP() []byte {
	file_orden_proto_rawDescOnce.Do(func() {
		file_orden_proto_rawDescData = protoimpl.X.CompressGZIP(file_orden_proto_rawDescData)
	})
	return file_orden_proto_rawDescData
}

var file_orden_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orden_proto_goTypes = []any{
	(*Customer)(nil),       // 0: Customer
	(*Vehicle)(nil),        // 1: Vehicle
	(*Compra)(nil),         // 2: Compra
	(*CompraResponse)(nil), // 3: CompraResponse
}
var file_orden_proto_depIdxs = []int32{
	1, // 0: Compra.vehiculos:type_name -> Vehicle
	0, // 1: Compra.cliente:type_name -> Customer
	2, // 2: CompraService.RealizarCompra:input_type -> Compra
	3, // 3: CompraService.RealizarCompra:output_type -> CompraResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orden_proto_init() }
func file_orden_proto_init() {
	if File_orden_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orden_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orden_proto_goTypes,
		DependencyIndexes: file_orden_proto_depIdxs,
		MessageInfos:      file_orden_proto_msgTypes,
	}.Build()
	File_orden_proto = out.File
	file_orden_proto_rawDesc = nil
	file_orden_proto_goTypes = nil
	file_orden_proto_depIdxs = nil
}
